version: '3.5'
services:
  mongodb:
    container_name: mongodb_container
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes: 
      - mongodb:/data/db
    ports: 
      - "27017:27017"
    networks: 
      - global
    restart: unless-stopped

volumes: 
  mongodb: