version: '3.5'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'mysqldata:/var/lib/mysql'
    networks:
        - global
volumes:
  mysqldata:
    driver: local